### ISSUE TITLE
Proper way to terminate session.

### ISSUE THREAD

**Issue by lukaszdworako** [kersny/airsim_nvidia_docker#5]
Currently every time I exit all tmux processes (px4, droneshell) stay running and clog up ports. Is there a specific way to exit the docker?

**Comment by kersny** [comment]
What I do is Ctrl-C each process and then use Ctrl-D to kill each tmux tab and then finally end the container.

`docker ps` should tell you if any docker containers are currently running and `docker kill` can be used to kill containers that are still running.
